=== smilique/FourthTask/src/test/resources/testdevices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:com.example"
           xmlns:xs="urn:com.example"
           elementFormDefault="qualified">

    <element name="devices">
        <complexType>
            <sequence>
                <element name="peripheralDevice" type="xs:peripheral" minOccurs="2" maxOccurs="unbounded"/>
                <element name="nonPeripheralDevice" type="xs:non-peripheral" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

        <complexType name="device">
            <sequence>
                <element name="type" >
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="mouse"/>
                            <enumeration value="keyboard"/>
                            <enumeration value="processor"/>
                            <enumeration value="motherboard"/>
                            <enumeration value="memory"/>
                            <enumeration value="webcam"/>
                            <enumeration value="FDD"/>
                        </restriction>
                    </simpleType>
                </element>
                <element name="name">
                    <simpleType>
                        <restriction base="string">
                            <pattern value="[\w+\\.,*\s]+"/>
                            <maxLength value="30"/>
                            <minLength value="3"/>
                        </restriction>
                    </simpleType>
                </element>
                <element name="price">
                        <simpleType>
                            <restriction base="double">
                                <minInclusive value="0"/>
                            </restriction>
                        </simpleType>
                </element>
                <element name="backlight" type="boolean"/>
            </sequence>
            <attribute name="id" use="required">
                <simpleType>
                <restriction base="ID">
                    <pattern value="([a-zA-Z])[a-zA-Z0-9]{4,7}"/>
                </restriction>
            </simpleType>
            </attribute>
            <attribute name="in-stock" default="false" type="boolean"/>
        </complexType>

    <complexType name="peripheral">
        <complexContent>
            <extension base="xs:device">
                <sequence>
                    <element name="connection" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="non-peripheral">
        <complexContent>
            <extension base="xs:device">
                <sequence>
                    <element name="slot" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== smilique/FourthTask/src/test/resources/testincorrectdevices.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="urn:com.example"
         xsi:schemaLocation="urn:com.example testdevices.xsd">

    <peripheralDevice id="a1111" in-stock="true">
        <type>keyboard</type>
        <name>Keyless Genesis</name>
        <price>75</price>
        <backlight>true</backlight>
        <connection>bluetooth</connection>
    </peripheralDevice>
    <peripheralDevice>
        <type>webcam</type>
        <name>Blindman Web Cam</name>
        <price>250</price>
        <backlight>false</backlight>
        <connection>USB</connection>
    </peripheralDevice>
    <nonPeripheralDevice id="c3333" in-stock="true">
        <type>motherboard</type>
        <name>MN1700 Motherboard</name>
        <price>740</price>
        <backlight>true</backlight>
        <connection>A1</connection>
    </nonPeripheralDevice>
    <nonPeripheralDevice id="d4444" in-stock="false">
        <type>processor</type>
        <name>Champion 34230X</name>
        <price>1400</price>
        <backlight>false</backlight>
        <slot>A1</slot>
    </nonPeripheralDevice>

</devices>
